import type { Metadata } from "next";
import {Manrope} from "next/font/google";
import "./globals.css";
import Head from "next/head";

const font = Manrope({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Interactive pricing component",
  description: "Generated by create next app by Ankur Jaiswal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <Head>
        <link rel="icon" type="image/png" sizes="32x32" href={"./assets/img/favicon-32x32.png"} />
      </Head>
      <body
        className={`${font.className} w-full min-h-screen font-semibold bg-white text-neutral-800 dark:bg-slate-900 dark:text-neutral-200`}
      >
        {children}
      </body>
    </html>
  );
}
