import type { Metadata } from "next";
import {Manrope} from "next/font/google";
import "./globals.css";
import Head from "next/head";
// import favicon from "@/app/assets/img/favicon-32x32.png"

const font = Manrope({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Interactive pricing component",
  description: "Generated by create next app by Ankur Jaiswal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/png" sizes="32x32" href={"favicon"} />
      </Head>
      <body
        className={`${font.className} w-full h-full min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
